version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: demo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro   # <-- run scripts on first init
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d orders"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
